name: Keep Repository Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次

permissions:
  contents: write

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make a dummy change
        run: |
          echo "Keeping the repository alive at $(date)" >> keep-alive.txt
          git config --local user.email "jayleecn@gmail.com"
          git config --local user.name "GitHub Actions"
          git add keep-alive.txt
          git commit -m "Keep repository alive: $(date)"

      - name: Push changes
        run: |
          git push origin HEAD:main