name: Daily Free BTC Alerts

on:
  schedule:
    - cron: '8 0,10 * * *'
    
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Vercel Deployment
      run: curl -X GET https://free-btc-alerts.vercel.app/api/index.js
